on:
  push:
  workflow_dispatch:


jobs:

  build_libretro:
    strategy:
      matrix:
        arch: [so64, x86, x64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/st1ll2@build
      with:
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}
