on:
  push:
  workflow_dispatch:


jobs:

  build_libretro:
    strategy:
      matrix:
        arch: [x86, x64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
      with:
        token: ${{ secrets.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@mingw-install
      with:
        arch: ${{ matrix.arch }}


    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ matrix.arch }}


    - shell: bash
      run: |
        merge () {
          echo "<<< ===  merging  $1  === >>>";
          if [[ -z "$2" ]]; then
            git merge origin/$1 || { git diff --diff-filter=U; exit 1; }
          else
            git merge origin/$1 || { git diff --diff-filter=U; git merge --abort; git merge -X $2 origin/$1; }
          fi
          echo "";
        }



    - shell: bash
      working-directory: ${{ github.workspace }}/src/os/libretro
      env:
        CC: ccache ${{ env.MINGW_CC }}
        CXX: ccache ${{ env.MINGW_CXX }}
      run: |
        make platform="win"



    - uses: actions/upload-artifact@main
      with:
        name: stella_libretro_${{ matrix.arch }}
        path: ${{ github.workspace }}/src/os/libretro/**.dll
